{{- if and .Values.canaryDelivery.create .Values.canaryDelivery.secretProviderClass.create (or .Values.canaryDelivery.deployment.envSecret .Values.canaryDelivery.deployment.fileShare.create) -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "microservice-chart.fullnameCanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labelsCanaryDelivery" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "microservice-chart.fullnameCanaryDelivery" $ }}
      type: Opaque
      data:
      {{- range $key, $objectName := .Values.canaryDelivery.deployment.envSecret }}
      - key: {{ $objectName }}
        objectName: {{ $objectName }}
      {{- end }}
      { { - if .Values.providedVolumeMount.create } }
      { { - range $key, $objectName := .Values.providedVolumeMount.envSecret } }
      - key: {{ $key }}
        objectName: {{ $objectName }}
      {{- end }}
{{/*#      {{- if .Values.canaryDelivery.deployment.fileShare.create }}*/}}
{{/*#      - key: azurestorageaccountname*/}}
{{/*#        objectName: azurestorageaccountname*/}}
{{/*#      - key: azurestorageaccountkey*/}}
{{/*#        objectName: azurestorageaccountkey*/}}
{{/*      {{- end }}*/}}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.keyvault.name }}
    tenantId: {{ .Values.keyvault.tenantId }}
    cloudName: ""
    objects: |
      array:
        {{- range $key, $objectName := .Values.canaryDelivery.deployment.envSecret }}
        - |
          objectName: {{ $objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- if .Values.providedVolumeMount.create }}
        {{- range $key, $objectName := .Values.providedVolumeMount.envSecret }}
        - |
          objectName: {{ $objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- end }}
{{- end }}
