{{- if and .Values.canaryDelivery.create .Values.canaryDelivery.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice-chart.fullnameCanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.forceSslRedirect | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize }}
    {{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- if and .Values.canaryDelivery.ingress.canary (eq .Values.canaryDelivery.ingress.canary.type "header") }}
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: {{ .Values.canaryDelivery.ingress.canary.weightPercent |quote }}
    nginx.ingress.kubernetes.io/canary-by-header: {{ .Values.canaryDelivery.ingress.canary.headerName |quote }}
    nginx.ingress.kubernetes.io/canary-by-header-value: {{ .Values.canaryDelivery.ingress.canary.headerValue |quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: beta-{{ include "microservice-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            pathType: {{ .Values.ingress.pathType }}
            {{- if eq .Values.canaryDelivery.ingress.canary.type "bluegreen" }}
            path: /beta{{ .Values.ingress.path }}
            {{- else }}
            path: {{ .Values.ingress.path }}
            {{- end }}
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.host | replace "." "-" }}
{{- end }}
