{{- if .Values.progressiveDelivery.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice-chart.fullnameProgressiveDelivery" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.forceSslRedirect | quote }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: pd-{{ include "microservice-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            path: /pd{{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.host | replace "." "-" }}
{{- end }}
