apiVersion: v2
name: devops-java-springboot-color-bar
description: An example application with Java spring boot
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.16.0
  repository: file://../../../charts/microservice-chart
